import ThemedScreen from '@components/ThemedScreen/ThemedScreen';
import { TestID } from '@enums/TestID';
import { useAuthStore } from '@providers/AuthProvider';
import styles from '@screens/TestScreen/TestScreen.styles';
import { apiClient } from '@services/ApiClient';
import { useState } from 'react';
import {
	Button,
	ScrollView,
	Text,
	TouchableOpacity,
	View,
} from 'react-native';
import {
	create,
	open,
	LinkTokenConfiguration,
	LinkExit,
	LinkSuccess,
	LinkAccount,
} from 'react-native-plaid-link-sdk';

interface Transaction {
	id: string;
	name: string;
	amount: number;
	date: string;
	category: string[];
}

const TestScreen = () => {
	const { logout } = useAuthStore();

	const [linkToken, setLinkToken] = useState<string | null>(null);
	const [_publicToken, setPublicToken] = useState<string | null>(null);
	const [isLinkReadyToOpen, setIsLinkReadyToOpen] = useState(false);
	const [accounts, setAccounts] = useState<LinkAccount[] | null>(null);
	const [transactions, _setTransactions] = useState<Transaction[] | null>(
		null,
	);
	// Insight is generated by an AI service after processing balances + transactions
	const [insight, _setInsight] = useState<string | null>(null);

	const handleCreate = async () => {
		if (!linkToken) {
			throw new Error('Link token is not set');
		}
		const linkConfig: LinkTokenConfiguration = { token: linkToken };
		create(linkConfig);
		setIsLinkReadyToOpen(true);
	};

	const handleOpen = () => {
		const openProps = {
			onSuccess: async (success: LinkSuccess) => {
				const institution = success.metadata.institution;
				const linkedAccounts = success.metadata.accounts;

				console.log('[Plaid Link] institution:', institution);
				console.log('[Plaid Link] accounts:', linkedAccounts);

				try {
					await apiClient.plaid.exchangePublicToken({
						publicToken: success.publicToken,
					});
					console.log(
						'[Plaid Link] Token exchanged successfully: ',
						success.publicToken,
					);
					setPublicToken(success.publicToken);
					setAccounts(linkedAccounts);
					setIsLinkReadyToOpen(false);
				} catch (error) {
					console.error(
						'[Plaid Link] Token exchange failed:',
						error,
					);
				}
			},
			onExit: (linkExit: LinkExit) => {
				console.log('[Plaid Link] Exit:', linkExit);

				// reset link token so user has to explicitly click "Create Link" again to re-open
				setLinkToken(null);
				setIsLinkReadyToOpen(false);
				setAccounts(null);
				_setTransactions(null);
				_setInsight(null);
			},
		};
		open(openProps);
	};

	const createDisabled = !linkToken || isLinkReadyToOpen;
	const openDisabled = !isLinkReadyToOpen;

	async function fetchLinkToken() {
		try {
			const result = await apiClient.plaid.getLinkToken();
			console.log('Fetched link token:', result.link_token);
			setLinkToken(result.link_token ?? null);
		} catch (error) {
			console.error('Error fetching link token:', error);
			setLinkToken(null);
		}
	}

	return (
		<ThemedScreen>
			<ScrollView
				contentContainerStyle={styles.scrollContent}
				testID={TestID.TestScreen}>
				<Text style={styles.text}>
					Welcome to the BudgetAI Test Screen!
				</Text>
				<Text style={styles.text}>{linkToken}</Text>

				<View style={styles.buttonContainer}>
					<TouchableOpacity
						style={[
							styles.button,
							createDisabled && styles.buttonDisabled,
						]}
						disabled={createDisabled}
						onPress={handleCreate}>
						<Text style={styles.buttonText}>Create Link</Text>
					</TouchableOpacity>
					<TouchableOpacity
						style={[
							styles.button,
							openDisabled && styles.buttonDisabled,
						]}
						disabled={openDisabled}
						onPress={handleOpen}>
						<Text style={styles.buttonText}>Open Link</Text>
					</TouchableOpacity>
				</View>

				{accounts && (
					<View style={styles.tableContainer}>
						<Text style={styles.tableTitle}>
							Linked Accounts
						</Text>
						<View style={styles.tableRow}>
							<Text
								style={[
									styles.tableCell,
									styles.tableHeader,
									styles.tableCellWide,
								]}>
								Name
							</Text>
							<Text
								style={[
									styles.tableCell,
									styles.tableHeader,
								]}>
								Type
							</Text>
							<Text
								style={[
									styles.tableCell,
									styles.tableHeader,
								]}>
								Mask
							</Text>
						</View>
						{accounts.map((a) => (
							<View key={a.id} style={styles.tableRow}>
								<Text
									style={[
										styles.tableCell,
										styles.tableCellWide,
									]}>
									{a.name}
								</Text>
								<Text style={styles.tableCell}>
									{String(a.subtype)}
								</Text>
								<Text style={styles.tableCell}>
									••{a.mask}
								</Text>
							</View>
						))}
					</View>
				)}

				{transactions && (
					<View style={styles.tableContainer}>
						<Text style={styles.tableTitle}>Transactions</Text>
						<View style={styles.tableRow}>
							<Text
								style={[
									styles.tableCell,
									styles.tableHeader,
									styles.tableCellWide,
								]}>
								Name
							</Text>
							<Text
								style={[
									styles.tableCell,
									styles.tableHeader,
								]}>
								Amount
							</Text>
							<Text
								style={[
									styles.tableCell,
									styles.tableHeader,
								]}>
								Date
							</Text>
						</View>
						{transactions.map((t) => (
							<View key={t.id} style={styles.tableRow}>
								<Text
									style={[
										styles.tableCell,
										styles.tableCellWide,
									]}>
									{t.name}
								</Text>
								<Text
									style={[
										styles.tableCell,
										t.amount < 0
											? styles.amountNegative
											: styles.amountPositive,
									]}>
									{t.amount < 0
										? `-$${Math.abs(t.amount).toFixed(
												2,
										  )}`
										: `+$${t.amount.toFixed(2)}`}
								</Text>
								<Text style={styles.tableCell}>
									{t.date}
								</Text>
							</View>
						))}
					</View>
				)}

				{insight && (
					<View style={styles.insightCard}>
						<Text style={styles.insightTitle}>AI Insight</Text>
						<Text style={styles.insightText}>
							{insight.trim()}
						</Text>
					</View>
				)}

				<Button title="Logout" onPress={logout} />

				<Button
					title="Fetch New Link Token"
					onPress={fetchLinkToken}
				/>
			</ScrollView>
		</ThemedScreen>
	);
};

export default TestScreen;
