import LinkedAccountsTable from '@components/LinkedAccountsTable/LinkedAccountsTable';
import ThemedScreen from '@components/ThemedScreen/ThemedScreen';
import TransactionsTable from '@components/TransactionsTable/TransactionsTable';
import { TestID } from '@enums/TestID';
import { usePlaidLink } from '@hooks/usePlaidLink';
import { useAuthStore } from '@providers/AuthProvider';
import styles from '@screens/TestScreen/TestScreen.styles';
import type { ApiClient } from '@services/ApiClient';
import { useState } from 'react';
import {
	Button,
	ScrollView,
	Text,
	TouchableOpacity,
	View,
} from 'react-native';
import { LinkAccount } from 'react-native-plaid-link-sdk';

interface Transaction {
	id: string;
	name: string;
	amount: number;
	date: string;
	category: string[];
}

const TestScreen = ({ apiClient }: { apiClient: ApiClient }) => {
	const { logout } = useAuthStore();

	const [accounts, setAccounts] = useState<LinkAccount[] | null>(null);
	const [transactions, setTransactions] = useState<Transaction[] | null>(
		null,
	);
	// Insight is generated by an AI service after processing balances + transactions
	const [insight, setInsight] = useState<string | null>(null);
	const { isStarting, startPlaidLink } = usePlaidLink({
		onLinkedAccounts: (linkedAccounts) => {
			setAccounts(linkedAccounts);
			setTransactions([
				// TODO: Replace with real transactions fetched from backend after receiving linked accounts
				{
					id: 'txn_1',
					name: 'Starbucks',
					amount: -4.5,
					date: '2024-04-20',
					category: ['Food and Drink', 'Coffee Shop'],
				},
				{
					id: 'txn_2',
					name: 'Payroll Deposit',
					amount: 2500,
					date: '2024-04-18',
					category: ['Income', 'Salary'],
				},
			]);
			setInsight(
				'Your recent transactions show a lot of spending on dining out. Consider setting a monthly budget for food and drink to save more!',
			);
		},
		onExit: (linkExit) => {
			console.debug('[Plaid Link] Exit:', linkExit);
		},
		exchangePublicToken: apiClient.plaid.exchangePublicToken,
		getLinkToken: apiClient.plaid.getLinkToken,
	});

	return (
		<ThemedScreen>
			<ScrollView
				contentContainerStyle={styles.scrollContent}
				testID={TestID.TestScreen}>
				<View style={styles.buttonContainer}>
					<TouchableOpacity
						style={[
							styles.button,
							isStarting && styles.buttonDisabled,
						]}
						disabled={isStarting}
						onPress={startPlaidLink}>
						<Text style={styles.buttonText}>
							{isStarting
								? 'Starting Plaid...'
								: 'Open Plaid Link'}
						</Text>
					</TouchableOpacity>
				</View>
				{accounts && <LinkedAccountsTable accounts={accounts} />}
				{transactions && (
					<TransactionsTable transactions={transactions} />
				)}
				{insight && (
					<View style={styles.insightCard}>
						<Text style={styles.insightTitle}>AI Insight</Text>
						<Text style={styles.insightText}>
							{insight.trim()}
						</Text>
					</View>
				)}
				<Button title="Logout" onPress={logout} />
			</ScrollView>
		</ThemedScreen>
	);
};

export default TestScreen;
