import ActionButtonList, {
	ActionButtonItem,
} from '@components/ActionButtonList/ActionButtonList';
import AppText from '@components/AppText/AppText';
import LinkedAccountsTable from '@components/LinkedAccountsTable/LinkedAccountsTable';
import PrimaryButton from '@components/PrimaryButton';
import ThemedScreen from '@components/ThemedScreen/ThemedScreen';
import TransactionsTable from '@components/TransactionsTable/TransactionsTable';
import { TestID } from '@enums/TestID';
import { usePlaidLink } from '@hooks/usePlaidLink';
import { NavigationService } from '@navigation/navigationService';
import { useApiClient } from '@providers/ApiClientProvider';
import { useAuthStore } from '@providers/AuthProvider';
import { useTheme } from '@providers/ThemeProvider';
import { createStyles } from '@screens/TestScreen/TestScreen.styles';
import { useCallback, useMemo, useState } from 'react';
import { ScrollView, View } from 'react-native';
import { LinkAccount } from 'react-native-plaid-link-sdk';

interface Transaction {
	id: string;
	name: string;
	amount: number;
	date: string;
	category: string[];
	merchant: string;
	transactionType: 'income' | 'expense' | 'transfer';
}

const TestScreen = () => {
	const { logout } = useAuthStore();
	const { colors } = useTheme();
	const styles = useMemo(() => createStyles(colors), [colors]);
	const actionItems = useMemo<ActionButtonItem[]>(
		() => [
			{
				id: 'go_back',
				title: 'Go Back',
				type: 'secondary',
				testID: 'TestScreen-GoBackButton',
			},
			{
				id: 'logout',
				title: 'Logout',
				type: 'tertiary',
				testID: 'TestScreen-LogoutButton',
			},
		],
		[],
	);
	const { exchangePublicToken, getLinkToken } = useApiClient(
		({ plaid }) => ({
			exchangePublicToken: plaid.exchangePublicToken,
			getLinkToken: plaid.getLinkToken,
		}),
	);

	const [accounts, setAccounts] = useState<LinkAccount[] | null>(null);
	const [transactions, setTransactions] = useState<Transaction[] | null>(
		null,
	);
	// Insight is generated by an AI service after processing balances + transactions
	const [insight, setInsight] = useState<string | null>(null);
	const { isStarting, startPlaidLink } = usePlaidLink({
		onLinkedAccounts: (linkedAccounts) => {
			setAccounts(linkedAccounts);
			setTransactions([
				// TODO: Replace with real transactions fetched from backend after receiving linked accounts
				{
					id: 'txn_1',
					name: 'Starbucks',
					amount: -4.5,
					date: '2024-04-20',
					category: ['Food and Drink', 'Coffee Shop'],
					merchant: 'Starbucks',
					transactionType: 'expense',
				},
				{
					id: 'txn_2',
					name: 'Payroll Deposit',
					amount: 2500,
					date: '2024-04-18',
					category: ['Income', 'Salary'],
					merchant: 'Foo',
					transactionType: 'income',
				},
			]);
			setInsight(
				'Your recent transactions show a lot of spending on dining out. Consider setting a monthly budget for food and drink to save more!',
			);
		},
		onExit: (linkExit) => {
			console.debug('[Plaid Link] Exit:', linkExit);
		},
		exchangePublicToken: exchangePublicToken,
		getLinkToken: getLinkToken,
	});

	const handleAction = useCallback(
		(itemId: string) => {
			if (itemId === 'logout') {
				logout();
				return;
			}

			if (itemId === 'go_back') {
				NavigationService.goBack();
			}
		},
		[logout],
	);

	return (
		<ThemedScreen>
			<ScrollView
				contentContainerStyle={styles.scrollContent}
				testID={TestID.TestScreen}>
				<View style={styles.heroCard}>
					<AppText variant="eyebrow" style={styles.eyebrow}>
						Sandbox
					</AppText>
					<AppText variant="title" style={styles.heroTitle}>
						Plaid + Insights
					</AppText>
					<AppText
						variant="bodyMedium"
						style={styles.heroSubtitle}>
						Link accounts and preview transactions with
						generated AI insight.
					</AppText>
					<PrimaryButton
						title={
							isStarting
								? 'Starting Plaid...'
								: 'Open Plaid Link'
						}
						onPress={() => {
							if (!isStarting) {
								startPlaidLink();
							}
						}}
						width="100%"
					/>
				</View>
				{accounts && <LinkedAccountsTable accounts={accounts} />}
				{transactions && (
					<TransactionsTable
						transactions={transactions.map((t) => ({
							id: t.id,
							name: t.name,
							amount: t.amount,
							date: t.date,
							category: t.category.join(', '),
							transactionType: t.transactionType,
							merchant: t.merchant,
						}))}
					/>
				)}
				{insight && (
					<View style={styles.insightCard}>
						<AppText
							variant="small"
							style={styles.insightTitle}>
							AI Insight
						</AppText>
						<AppText variant="body" style={styles.insightText}>
							{insight.trim()}
						</AppText>
					</View>
				)}
				<ActionButtonList
					items={actionItems}
					onPressItem={handleAction}
				/>
				<View style={styles.bottomSpacer} />
			</ScrollView>
		</ThemedScreen>
	);
};

export default TestScreen;
